# Generated by Django 4.2.2 on 2023-06-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("post", "0002_rename_likespeople_post_like_people_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(help_text="댓글")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정 일자"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="댓글 작성중인 게시글",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.post",
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        help_text="댓글 작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글",
                "db_table": "reply",
                "ordering": ["-created_at"],
            },
        ),
    ]
