# Generated by Django 4.2.2 on 2023-06-22 06:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myself", models.TextField()),
                (
                    "mobile_phone",
                    models.CharField(
                        help_text="연락처",
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="\\d{2,3}-\\d{3,4}-d{4}"
                            )
                        ],
                    ),
                ),
                ("company", models.CharField(help_text="직장", max_length=100)),
                ("education", models.CharField(max_length=50)),
                ("residence", models.CharField(max_length=255)),
                ("birth_place", models.CharField(max_length=255)),
                (
                    "friends",
                    models.ManyToManyField(blank=True, to="profiles.userprofile"),
                ),
                (
                    "profile_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="친구 요청 발생 시간"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        help_text="친구 요청 수신",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_received",
                        to="profiles.userprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="친구 요청 발신",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests_sent",
                        to="profiles.userprofile",
                    ),
                ),
            ],
        ),
    ]
