# Generated by Django 4.2.2 on 2023-06-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="is_accepted",
            field=models.BooleanField(default=False, help_text="친구 요청 수락 여부"),
        ),
    ]
