# Generated by Django 4.2.2 on 2023-06-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_userprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth_place",
            field=models.CharField(help_text="출생지", max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.CharField(help_text="학력", max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="myself",
            field=models.TextField(help_text="소개글"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="residence",
            field=models.CharField(help_text="거주지", max_length=255),
        ),
    ]
