# Generated by Django 4.2.2 on 2023-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        default="", max_length=100, unique=True, verbose_name="이메일"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입 일시"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="최종 로그인 일시"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("is_admin", models.BooleanField(default=False, verbose_name="스태프 여부")),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저",
            },
        ),
    ]
