import { useNavigate } from "react-router-dom";
import profile_img5 from "../img/profile_img5.png";

const Header = ({ type }) => {
  const navigate = useNavigate();
  const onClickHome = () => {
    navigate("/");
  };
  const onClickAbout = () => {
    navigate("/about");
  };
  const onClickFriends = () => {
    navigate("/friends");
  };
  const onClickPhotos = () => {
    navigate("/photos");
  };
  const onClickVideos = () => {
    navigate("/videos");
  };
  const onClickMap = () => {
    navigate("/map");
  };
  return (
    <div
      className="
    ProfileSectio 
    max-w-7xl 
    my-0 
    mx-auto
    "
    >
      <section
        className="
      w-full h-460
      bg-gradient-to-b from-neutral-200 to-neutral-500 
      rounded-lg 
      relative"
      >
        <div
          className="
        flex 
        flex-col 
        relative"
        >
          <button
            className="
          p-1 
          w-[160px] 
          h-[40px] 
          absolute 
          text-white  
          bg-neutral-600 
          rounded-md 
          top-80 
          right-11 
          hover:brightness-[80%]
          "
          >
            😀아바타로 만들기
          </button>
          <button
            className="
          p-1 
          w-[160px] 
          h-[40px] 
          absolute 
          text-white 
          bg-neutral-600 
          rounded-md 
          top-96 
          right-11 
          hover:brightness-[80%]
          "
          >
            📷커버 사진 추가
          </button>
        </div>
      </section>
      <section
        className="
      w-[1186px] 
      h-[146px] 
      relative 
      flex 
      justify-betwee 
      my-0 mx-auto
      "
      >
        <div
          className="
        flex 
        relative 
        w-[175px]
        "
        >
          <div
            className="
          absolute 
          top-[-20px] 
          w-[168px] 
          h-[168px] 
          rounded-full 
          border-4 
          border-white  
          "
          >
            <img
              className="
              rounded-full  
              cursor-pointer
              hover:brightness-[90%]
              "
              alt="profile"
              src={profile_img5}
            />
          </div>
        </div>
        <div
          className="
        w-[600px] 
        flex-1
        "
        >
          <h1 className="text-lg">user name</h1>
          <span>user friends 00명</span>
        </div>
        <div
          className="
        w-[505px] 
        flex 
        justify-end 
        items-end 
        "
        >
          <button
            className="
          w-[160px] 
          h-[40px]  
          bg-blue-600 
          rounded-md 
          top-80 
          right-11 
          hover:brightness-[92%] 
          mx-[5px] text-white
          "
          >
            + 스토리에 추가
          </button>
          <button
            className="
          w-[160px] 
          h-[40px]  
          bg-neutral-300 
          rounded-md 
          top-80 
          right-11 
          hover:brightness-[92%] 
          mx-[5px]
          "
          >
            ✏️프로필 편집
          </button>
          <button
            className="
          w-[40px] 
          h-[40px]  
          bg-neutral-300 
          rounded-md 
          top-80 
          right-11 
          hover:brightness-[92%] 
          mx-[5px]
          "
          >
            ▼
          </button>
        </div>
      </section>
      <section
        className="
      w-[1186px] 
      my-0 mx-auto
      "
      >
        <hr
          className="
        w-full 
        border-t-[1px] 
        border-slate-500 
        mt-3.5
        "
        />
        <div
          className="
        flex 
        items-center 
        justify-center 
        pt-2	
        "
        >
          <div
            className="
          w-[1136px] 
          h-[40px] 
          flex
          "
          >
            <span
              className="
              flex items-center justify-center 
              px-[10px] 
              cursor-pointer
              text-blue-600
              font-bold
              underline
              underline-offset-[20px]
              decoration-2
              
             "
              onClick={onClickHome}
            >
              게시물
            </span>
            <span
              className="
              flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%]
              cursor-pointer
              "
              onClick={onClickAbout}
            >
              정보
            </span>
            <span
              className="
              flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%] 
              cursor-pointer"
              onClick={onClickFriends}
            >
              친구
            </span>
            <span
              className="
              flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%] 
              cursor-pointer"
              onClick={onClickPhotos}
            >
              사진
            </span>
            <span
              className="
              flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%] 
              cursor-pointer"
              onClick={onClickVideos}
            >
              동영상
            </span>
            <span
              className="
              flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%] 
              cursor-pointer"
              onClick={onClickMap}
            >
              체크인
            </span>
            <span
              className="flex 
              items-center 
              justify-center 
              px-[10px]
            bg-white 
              rounded-md 
              top-80 
              right-11 
              hover:brightness-[92%] 
              cursor-pointer"
            >
              더보기▼
            </span>
          </div>
          <div
            className="
          w-[40px] 
          h-[40px] 
          bg-neutral-300 
          rounded-md 
          hover:brightness-[92%] 
          flex 
          justify-center 
          cursor-pointer
          "
          >
            ...
          </div>
        </div>
      </section>
    </div>
  );
};

export default Header;
